version: '3.4'

networks:
  usermessage:

services:
  message.api:
    container_name: messageapi
    image: ${DOCKER_REGISTRY-}messageapi
    build:
      context: .
      dockerfile: MicroServices/Message/Message.API/Dockerfile
    networks:
      - usermessage
    depends_on:
      - usermessagedb
    environment:
      - DB_HOST=usermessagedb
      - DB_DATABASE=MessageDB
      - DB_USER=sa
      - DB_MSSQL_SA_PASSWORD=Pwd123!!3
 
  user.api:
    container_name: userapi
    image: ${DOCKER_REGISTRY-}userapi
    build:
      context: .
      dockerfile: MicroServices/User/User.API/Dockerfile
    networks:
      - usermessage
    depends_on:
      - usermessagedb
    environment:
      - DB_HOST=usermessagedb
      - DB_DATABASE=UserDB
      - DB_USER=sa
      - DB_MSSQL_SA_PASSWORD=Pwd123!!3

  usermessagedb:
    container_name: usermessagedb
    image: mcr.microsoft.com/mssql/server:2019-latest
    networks:
      - usermessage
    ports:
      - "1433:1433"
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=Pwd123!!3
      - MSSQL_PID=Developer

  mosquitto:
    container_name: mosquitto
    image: eclipse-mosquitto
    hostname: mosquitto
    restart: unless-stopped
    volumes:
      - ./mosquitto:/etc/mosquitto:rw
      - ./mosquitto/mosquitto.conf:/mosquitto/config/mosquitto.conf
    networks:
      - usermessage
    ports:
      - "1883:1883"


