version: '3.4'

networks:
  usermessage:
  grpc:

services:
  message.api:
    container_name: messageapi
    image: ${DOCKER_REGISTRY-}messageapi
    build:
      context: .
      dockerfile: MicroServices/Message/Message.API/Dockerfile
    networks:
      - usermessage
    depends_on:
      - usermessagedb
    environment:
      - DB_HOST=usermessagedb
      - DB_DATABASE=MessageDB
      - DB_USER=sa
      - DB_MSSQL_SA_PASSWORD=Pwd123!!3
 
  user.api:
    container_name: userapi
    image: ${DOCKER_REGISTRY-}userapi
    build:
      context: .
      dockerfile: MicroServices/User/User.API/Dockerfile
    networks:
      - usermessage
    depends_on:
      - usermessagedb
    environment:
      - DB_HOST=usermessagedb
      - DB_DATABASE=UserDB
      - DB_USER=sa
      - DB_MSSQL_SA_PASSWORD=Pwd123!!3

  usermessagedb:
    container_name: usermessagedb
    image: mcr.microsoft.com/mssql/server:2019-latest
    networks:
      - usermessage
    ports:
      - "1433:1433"
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=Pwd123!!3
      - MSSQL_PID=Developer

  mosquitto:
    container_name: mosquitto
    image: eclipse-mosquitto
    hostname: mosquitto
    restart: unless-stopped
    volumes:
      - ./mosquitto:/etc/mosquitto:rw
      - ./mosquitto/mosquitto.conf:/mosquitto/config/mosquitto.conf
    networks:
      - usermessage
    ports:
      - "1883:1883"

  grpc.client:
    container_name: GrpcClient
    image: ${DOCKER_REGISTRY-}grpcclient
    build:
      context: .
      dockerfile: MicroServices/gRPC/gRPC.client/Dockerfile
    networks:
      - grpc
    depends_on:
      - grpc.server
    ports:
      - "9000:9000"
    environment:
      GRPC_SERVER_PORT: 7002
      GRPC_SERVER_HOST: grpc.server
  
  grpcmessagedb:
    container_name: grpcmessagedb
    image: mcr.microsoft.com/mssql/server:2019-latest
    networks:
      - grpc
    ports:
      - "1432:1432"
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=Pwd123!!1
      - MSSQL_PID=Developer

  grpc.server:
    container_name: GrpcServer
    image: ${DOCKER_REGISTRY-}grpcserver
    build:
      context: .
      dockerfile: MicroServices/gRPC/gRPC.server/Dockerfile
    networks:
      - grpc
    depends_on:
      - grpcmessagedb
    ports: 
      - "7002:7002"
    environment: 
      DB_HOST: 'grpcmessagedb'
      DB_NAME: 'GrpcMessageDb'
      DB_USERSA: 'sa'
      DB_MSSQL_SA_PASSWORD: 'Pwd123!!1'
      DB_PORT: 1432
